# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{giggly}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Vandgrift", "Adam Hunter"]
  s.date = %q{2009-10-12}
  s.description = %q{breaks the gigya web api down into idiomatic ruby for your coding pleasure.}
  s.email = %q{somethingfamiliar@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "VERSION",
     "javascripts/giggly-socialize-min.js",
     "javascripts/giggly-socialize.js",
     "lib/giggly.rb",
     "lib/giggly/friend.rb",
     "lib/giggly/javascript.rb",
     "lib/giggly/javascript/helper.rb",
     "lib/giggly/javascript/socialize.rb",
     "lib/giggly/rest.rb",
     "lib/giggly/rest/request.rb",
     "lib/giggly/rest/socialize.rb",
     "lib/giggly/session_info.rb",
     "lib/giggly/user.rb",
     "test/fake_socialize.rb",
     "test/giggly/friend_test.rb",
     "test/giggly/javascript/helper_test.rb",
     "test/giggly/javascript/socialize_test.rb",
     "test/giggly/rest/request_test.rb",
     "test/giggly/rest/socialize_test.rb",
     "test/giggly/user_test.rb",
     "test/responses/disconnect.yml",
     "test/responses/get_friends_info.yml",
     "test/responses/get_raw_data.yml",
     "test/responses/get_session_info.yml",
     "test/responses/get_user_info.yml",
     "test/responses/publish_user_action.yml",
     "test/responses/send_notification.yml",
     "test/responses/set_status.yml",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/sfamiliar/giggly}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{wrapper for the gigya rest and javascript apis}
  s.test_files = [
    "test/fake_socialize.rb",
     "test/giggly/friend_test.rb",
     "test/giggly/javascript/helper_test.rb",
     "test/giggly/javascript/socialize_test.rb",
     "test/giggly/rest/request_test.rb",
     "test/giggly/rest/socialize_test.rb",
     "test/giggly/user_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, ["= 0.4.5"])
      s.add_runtime_dependency(%q<ruby-hmac>, ["= 0.3.2"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 2.10.1"])
      s.add_development_dependency(%q<jnunemaker-matchy>, ["= 0.4.0"])
      s.add_development_dependency(%q<mocha>, ["= 0.9.4"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.5"])
      s.add_development_dependency(%q<redgreen>, [">= 1.0.0"])
    else
      s.add_dependency(%q<httparty>, ["= 0.4.5"])
      s.add_dependency(%q<ruby-hmac>, ["= 0.3.2"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 2.10.1"])
      s.add_dependency(%q<jnunemaker-matchy>, ["= 0.4.0"])
      s.add_dependency(%q<mocha>, ["= 0.9.4"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.5"])
      s.add_dependency(%q<redgreen>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<httparty>, ["= 0.4.5"])
    s.add_dependency(%q<ruby-hmac>, ["= 0.3.2"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 2.10.1"])
    s.add_dependency(%q<jnunemaker-matchy>, ["= 0.4.0"])
    s.add_dependency(%q<mocha>, ["= 0.9.4"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.5"])
    s.add_dependency(%q<redgreen>, [">= 1.0.0"])
  end
end
